from fastapi import FastAPI
from utils import Utils, Logger

app = FastAPI()
util = Utils()


@app.post('/recepits/{id}/points')
async def process_reciepts(id: str):
    """
    Takes in a JSON receipt (see example in the example directory) and returns a 
    JSON object with an ID generated by your code.

    The ID returned is the ID that should be passed into /receipts/{id}/points to 
    get the number of points the receipt was awarded.

    How many points should be earned are defined by the rules below.

    Reminder: Data does not need to survive an application restart. This is to allow 
    you to use in-memory solutions to track any data generated by this endpoint.

    { "id": "7fb1377b-b223-49d9-a31a-5a02701dd310" }
    """
    id = util.create_id()
    return {'id': id}


@app.get('/recepits/process')
async def get_points(data):
    """
    A simple Getter endpoint that looks up the receipt by the ID and returns an object 
    specifying the points awarded.

    { "points": 32 }
    """
    points, message = util.calcuate(data)
    Logger().start_debug(message)

    return {'points': points}
